!configuration
clusterName: Enterprise Telemetry Monitor
masterAddresses: 127.0.0.1:9300
# Name of the node. Defaults to the hostname of the machine running on.
#nodeName: 
# The interval in milliseconds between each flush requests. Defaults to 30000, which means every 30 seconds is a flush of 
# the documents to the database requested.
#flushInterval: 
queueManagers: 
- !queueManager
# The name of the queuemanager to connect to.
   name: QMGR
# The channel used to connect to the queue manager  
#   channel: 
# The host of the queuemanager. This can be an ip address, or the host name of the server the queuemanager is running on.
   host: 127.0.0.1
# The port the queuemanager is listening on.   
   port: 1414   
   destinations: 
   - !destination
# Name of the queue to read messages from.   
      name: QUEUE.IN.1
# The number of listeners on the queue. This is basically the number of connections to the queuemanager and the 
# number of threads that are processing messages from the queue. In most situations a single thread per queue
# is sufficient.
      nrOfListeners: 1
# The type of messages that are read from the queue. This can be one of 'auto', 'clone', 'iibevent', 'etmevent':
# - auto: the processor is auto detecting which kind of message is read. This isn't a recommended setting for high performance situations.
# - clone: the processor is assuming the read message is a clone from the original message.
# - iibevent: the processor is assuming the content of the message is an IIB event, generated by an IIB instance. See https://www-01.ibm.com/support/knowledgecenter/SSMKHH_9.0.0/com.ibm.etools.mft.doc/ac60386_.htm for more information.
# - etmevent: the processor is assuming the content of the message is an ETM event.
      messageTypes: auto
# The MQ commit size. Messages are read in an unit of work. Each unit of work has a max of 'commitSize' messages or takes as long 
# as 'commitInterval' milliseconds. commitSize defaults to 500, and commitInterval defaults to 10000. This means a MQ transaction 
# never contains more than 500 messages and never takes longer than 10 seconds.
#      commitSize: 
#      commitInterval: 
# The MQ get options used to get messages from the destination. Defaults to the calculated value of CMQC.MQGMO_WAIT + CMQC.MQGMO_FAIL_IF_QUIESCING + CMQC.MQGMO_CONVERT + CMQC.MQGMO_SYNCPOINT + CMQC.MQGMO_LOGICAL_ORDER + CMQC.MQGMO_ALL_SEGMENTS_AVAILABLE + CMQC.MQGMO_COMPLETE_MSG
#      destinationGetOptions:
# The MQ open options used to acces the destination. Defaults to the calculated value of CMQC.MQOO_INQUIRE + CMQC.MQOO_FAIL_IF_QUIESCING + CMQC.MQOO_INPUT_SHARED
#      destinationOpenOptions:
   - !destination
      name: QUEUE.IN.2
      nrOfListeners: 1
      messageTypes: clone
