!configuration
clusterName: Enterprise Telemetry Monitor
masterAddresses: 127.0.0.1:9300
# nodeName: 
queueManager: 
# The name of the queuemanager to connect to.
   name: QMGR
# The channel used to connect to the queue manager  
#   channel: 
# The host of the queuemanager. This can be an ip address, or the host name of the server the queuemanager is running on.
   host: 127.0.0.1
# The port the queuemanager is listening on.   
   port: 1414   
   destinations: 
   - !destination
# Name of the queue to read messages from.   
      name: QUEUE.IN.1
# The number of listeners on the queue. This is basically the number of connections to the queuemanager and the 
# number of threads that are processing messages from the queue. In most situations a single thread per queue
# is sufficient.
      nrOfListeners: 1
# The type of messages that are read from the queue. This can be one of 'auto', 'clone', 'iibevent', 'etmevent':
# - auto: the processor is auto detecting which kind of message is read. In high performance situations this isn't a recommended setting.
# - clone: the processor is assuming the read message is a clone from the original message.
# - iibevent: the processor is assuming the content of the message is an IIB event, generated by an IIB instance. See https://www-01.ibm.com/support/knowledgecenter/SSMKHH_9.0.0/com.ibm.etools.mft.doc/ac60386_.htm for more information.
# - etmevent: the processor is assuming the content of the message is an ETM event.
      messageTypes: auto
   - !destination
      name: QUEUE.IN.2
      nrOfListeners: 1
      messageTypes: clone