!configuration
clusterName: etm_test_mark
masterAddresses: 127.0.0.1:9300
nodeName: 
queueManager: 
   name: EBOCGW01
   channel: WMQ.TST
   host: ami-cgw-ontw.hosting.corp
   port: 5704
   destinations: 
   - !destination
      name: AA001730.REQ
      nrOfListeners: 5
   - !destination
      name: AA003696.REQ
      nrOfListeners: 5
   - !destination
      name: AA003711.REQ
      nrOfListeners: 5
   - !destination
      name: AA004579.REQ
      nrOfListeners: 5
   - !destination
      name: AA006610.REQ
      nrOfListeners: 5