apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: etm-demo
  labels:
    app: "elasticsearch"
    component: "client"
    release: "${elasticsearch-version}"
  name: "elasticsearch-client"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "elasticsearch"
      component: "client"
      release: "${elasticsearch-version}"
  template:
    metadata:
      labels:
        app: "elasticsearch"
        component: "client"
        release: "${elasticsearch-version}"
    spec:
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "elasticsearch"
                  component: "client"
      initContainers:
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      # and https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall
      - name: "sysctl"
        image: "busybox"
        imagePullPolicy: "Always"
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: "elasticsearch"
        env:
        - name: cluster.name
          value: etm-demo-01
        - name: node.master
          value: "false"
        - name: node.data
          value: "false"
        - name: node.ingest
          value: "false"
        - name: discovery.seed_hosts
          value: "elasticsearch-discovery"
        - name: cluster.initial_master_nodes
          value: "elasticsearch-discovery"
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms512M -Xmx512M"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 90          
        image: "docker.elastic.co/elasticsearch/elasticsearch-oss:${elasticsearch-version}"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
