apiVersion: v1
kind: Service
metadata:
  labels:
    app: "etm"
    component: "client"
    release: "${etm-version}"
  name: "etm-client"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
      targetPort: http
  selector:
    app: "etm"
    component: "client"
    release: "${etm-version}"
