apiVersion: v1
kind: Service
metadata:
  namespace: etm-demo
  labels:
    app: "elasticsearch"
    component: "client"
    release: "${elasticsearch-version}"
  name: "elasticsearch-client"
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: http
      targetPort: http
    - port: 9300
      targetPort: transport
      name: transport
  selector:
    app: "elasticsearch"
    component: "client"
    release: "${elasticsearch-version}"
